### ISSUE TITLE
Correct Arabic Language "this is not an issue, only suggestion"  

### ISSUE THREAD

**Issue by xcode-ae** [fairsketch/RISE-Translation#32]
Good day,
 we would like to help you guys regarding arabic language translation , we found unprofessional sentences has been used ,
 example for :$lang["client_can_view_tasks"] ="يمكن للعميل عرض المهام؟"; if you want more professional you have to add "هل" on the start (هل يمكن للعميل عرض المهام ؟) we used "هل " to make sure if you want to allow or active ,
 if you allow us so we can try to give you our experiences for fixing them .

BTW we love your works guys 
regards.

**Comment by fairsketch** [comment]
Hi,

Thanks for you suggestions. The translations are not done by us. Different customers sending the translations. If you would like to improve the translation, you can do pull request on the github. 



Best Regards,

Fairsketch Team.








---- On Thu, 12 Jan 2023 20:57:15 +0600 Xcode Technology ***@***.***> wrote ---





Good day,
 we would like to help you guys regarding arabic language translation , we found unprofessional sentences has been used ,
 example for :$lang["client_can_view_tasks"] ="يمكن للعميل عرض المهام؟"; if you want more professional you have to add "هل" on the start (هل يمكن للعميل عرض المهام ؟) we used "هل " to make sure if you want to allow or active ,
 if you allow us so we can try to give you our experiences for fixing them .
BTW we love your works guys
 regards.
